name: Update NPM Package

on:
  push:
    branches:
      - main # You can specify the branch you want to trigger this workflow on

jobs:
  update-npm:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: npm install
      
    - name: Update NPM Package
      run: |
        # Replace 'github_username/repo_name' with the actual GitHub repository URL.
        REPO_URL="https://github.com/angeloViggiani7/ra-sheetsdb-dataprovider.git"
        
        # Replace 'folder' with the folder containing the NPM package.
        PACKAGE_DIR="ra-sheetsdb-dataprovider"
        
        # Clone the GitHub repository.
        git clone "https://github.com/angeloViggiani7/ra-sheetsdb-dataprovider.git"
        
        # Copy updated files to the NPM package folder.
        cp -r "$PACKAGE_DIR"
        
        # Commit and push the changes.
        cd "$PACKAGE_DIR"
        git config user.email "vangelowork@gmail.com"
        git config user.name "angeloViggiani7"
        git add .
        git commit -m "Update NPM package from GitHub repository"
        git push
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
